### ISSUE TITLE
fix potential mixup at subjects

### ISSUE THREAD

**Issue by mtlhdnrd** [mtlhdnrd/exam_prep#12]
where the program checks which subject a topic belongs to, it uses the `tantargyid` field in the sql with the same IDs hardcoded into the program later when it's used, even though the database has a separate table just for this. this could cause issues if the subjects are added to the database in a different order. easy fix, shouldn't take long.

**Comment by mtlhdnrd** [comment]
same thing in add.php:107 dropdown from commit 104dead
please retrieve those from the database as well

**Comment by mtlhdnrd** [comment]
> same thing in add.php:107 dropdown from commit [104dead](https://github.com/mtlhdnrd/exam_prep/commit/104deada3e39ef624d1ce841cf2b0d8cfc6823c1) please retrieve those from the database as well

i just checked, that commit replaced a correct-looking solution...
what are you doing, man?

**Comment by IDcorrupt** [comment]
didn't commit anything yet

**Comment by IDcorrupt** [comment]
because the database changed
back then the database had class names instead of class id-s
