### ISSUE TITLE
switch case true false

### ISSUE THREAD

**Issue by IDcorrupt** [mtlhdnrd/exam_prep#14]
![image](https://github.com/mtlhdnrd/exam_prep/assets/82838105/615bcfae-2498-47e6-a353-42d50b20ea71)

**Comment by mtlhdnrd** [comment]
you didnt seriously create an issue for this, right? commit messages exist for this exact reason. you can just write code without creating an issue for it. how many fucking commits did i do that fixed a small fuckup or idiocy of yours? with just a couple of lines changed? issues are for bigger things, issues, hence the name, that take longer. or that will need fixing but you cant get to it right away, to help track it. just fix the code, commit with the message "i was stupid, fixed [idiocy here]", merge and push.
and dont fuck up my labels. "womp womp" isnt very descriptive. and defintely doesnt deserve its own label.

**Comment by mtlhdnrd** [comment]
oh fuck you can still comment
and self-assigning after completion? i can see that youve done it regardless. assigning is a preliminary action.
