### ISSUE TITLE
add.php dropdown issues

### ISSUE THREAD

**Issue by mtlhdnrd** [mtlhdnrd/exam_prep#15]
it automatically selects the first subject instead of showing the question like it's supposed to
add selected to the option containing the question, and check if it has been changed at submission

**Comment by IDcorrupt** [comment]
it doesn't select the question because of the disabled tag you added in 5b06a91523226040036ad4c5306b1cce77996159

**Comment by IDcorrupt** [comment]
so do i remove the disabled tag or do I add the selected tag next to the disabled tag (which sounds weird to me but HTML often sounds weird to me)

**Comment by IDcorrupt** [comment]
ok i add both

**Comment by mtlhdnrd** [comment]
you add selected. html can select anything, `disabled` is just a restriction for the user

**Comment by mtlhdnrd** [comment]
"Warning: Undefined array key "class" in C:\xampp\htdocs\exam_prep\main\add.php on line 26"
if you try to add a topic without selecting a subject, it does throw it back along with the toast, but it also gives this error

**Comment by IDcorrupt** [comment]
didn't do that before, great

**Comment by IDcorrupt** [comment]
ok so disabled option doesn't send value back

**Comment by mtlhdnrd** [comment]
> ok so disabled option doesn't send value back

why would it? disabled => you can't submit that, that's not a valid option
